service: people-api

provider:
  name: aws
  region: us-east-2
  runtime: provided.al2
  stage: ${opt:stage, 'prod'}

  vpc:
    securityGroupIds:
      - sg-05e398cb59137fefd
    subnetIds:
      - subnet-06e9211b717e5a359
      - subnet-0338c9602f36d2b3d

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rds-db:connect
          Resource: arn:aws:rds:${aws:region}:${aws:accountId}:db:*
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"

  environment:
    APP_ENV: production
    DB_CONNECTION: ${ssm:/people-api/DB_CONNECTION}
    DB_HOST: ${ssm:/people-api/DB_HOST}
    DB_PORT: ${ssm:/people-api/DB_PORT}
    DB_DATABASE: ${ssm:/people-api/DB_DATABASE}
    DB_USERNAME: ${ssm:/people-api/DB_USERNAME}
    DB_PASSWORD: ${ssm:/people-api/DB_PASSWORD}

plugins:
  - ./vendor/bref/bref
  - serverless-offline

package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
    - "!storage/logs/**"
    - "!.git/**"

functions:
  api:
    handler: public/index.php
    timeout: 28
    layers:
      - ${bref:layer.php-82-fpm}
    events:
      - http:
        path: /api/{proxy+}
        method: ANY
        cors: true
    environment:
      L5_SWAGGER_GENERATE_ALWAYS: ${ssm:/people-api/L5_SWAGGER_GENERATE_ALWAYS}
      L5_SWAGGER_CONST_HOST: ${ssm:/people-api/L5_SWAGGER_CONST_HOST}
      SWAGGER_GENERATE_ALWAYS: true
      SWAGGER_CONST_HOST: ${self:custom.apiUrl}
      APP_DEBUG: true
      APP_STORAGE: /tmp
      VIEW_COMPILED_PATH: /tmp/views
      CACHE_DRIVER: array
      LOG_CHANNEL: stderr

  artisan:
    handler: artisan
    timeout: 120
    layers:
      - ${bref:layer.php-82}
      - ${bref:layer.console}

custom:
  apiUrl: https://k6yxy5gbs5.execute-api.us-east-2.amazonaws.com/prod/api/
